name: Save Provider Open Positions

on:
  schedule:
    - cron: "0 0 * * *"    # 00:00
    - cron: "1 0 * * *"    # 00:00
    - cron: "0 1 * * *"    # 01:00
    - cron: "1 1 * * *"    # 01:00
    - cron: "0 3 * * *"    # 03:00
    - cron: "1 3 * * *"    # 03:00
    - cron: "0 4 * * *"    # 04:00
    - cron: "1 4 * * *"    # 04:00
    - cron: "0 6 * * *"    # 06:00
    - cron: "1 6 * * *"    # 06:00
    - cron: "0 7 * * *"    # 07:00
    - cron: "1 7 * * *"    # 07:01
    - cron: "0 8 * * *"    # 08:00
    - cron: "1 8 * * *"    # 08:00
    - cron: "0 10 * * *"   # 10:00
    - cron: "1 10 * * *"   # 10:00
    - cron: "0 12 * * *"   # 12:00
    - cron: "1 12 * * *"   # 12:00
    - cron: "0 13 * * *"   # 13:00
    - cron: "1 13 * * *"   # 13:00
    - cron: "0 14 * * *"   # 14:00
    - cron: "1 14 * * *"   # 14:00
    - cron: "0 15 * * *"   # 15:00
    - cron: "1 15 * * *"   # 15:00
    - cron: "0 16 * * *"   # 16:00
    - cron: "1 16 * * *"   # 16:00
    - cron: "0 17 * * *"   # 17:00
    - cron: "1 17 * * *"   # 17:00
    - cron: "0 18 * * *"   # 18:00
    - cron: "1 18 * * *"   # 18:00
    - cron: "0 19 * * *"   # 19:00
    - cron: "1 19 * * *"   # 19:00
    - cron: "0 20 * * *"   # 20:00
    - cron: "1 20 * * *"   # 20:00
    - cron: "0 21 * * *"   # 21:00
    - cron: "1 21 * * *"   # 21:00
    - cron: "0 22 * * *"   # 22:00
    - cron: "1 22 * * *"   # 22:00
    - cron: "0 23 * * *"   # 23:00
    - cron: "1 23 * * *"   # 23:00
  workflow_dispatch:

permissions:
  contents: write   # IMPORTANT: allows committing to repo

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and save JSON
        env:
          FA_EMAIL: ${{ secrets.FA_EMAIL }}
          FA_PASSWORD: ${{ secrets.FA_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          PROVIDER_ID: "931"
          OUT_DIR: open_positions
        run: |
          python save_open_positions.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add open_positions/*.json

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update open positions for provider ${{ inputs.provider_id }}"
          git push
